define(['jquery','Module',"commonData"],function($,Module,commonData){
	new Module({
		type:"navLeft",
		obj:'indexNav',
		data:[{
			id:1,
			value:"线下数据",
			data:["本店转化","周边客流",'人物画像','到店顾客','回头客分析','门店排名','店内热力图','用户轨迹']
		},{
			id:2,
			value:"内容管理",
			data:[]
		},{
			id:3,
			value:"互动商品管理",
			data:[]
		},{
			id:4,
			value:"店铺管理"
		}]
	})
})